name: Run TMDB Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Versão do Python que você deseja usar

    - name: Stash changes
      run: |
        git stash --include-untracked
        echo "Stashed changes if any"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Pop stashed changes
      run: |
        git stash pop || echo "No changes to stash pop"

    - name: Run TMDB script
      run: python extrair.py  # Substitua pelo nome do seu script Python
      env:
        TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
